4. 댓글 작성 API 개발_domain 부터 controller 개발 및 테스트 완료
DSS-1st/realworld pull request #11
Opened 2023-05-02 04:49 UTC by sdongpil

검토 부탁드립니다.

2023-05-02 12:49 UTC, Rebwon requested changes
수고하셨습니다! 몇 가지 의견을 남겼으니, 확인 부탁드립니다.

2023-05-02 12:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleRequestDto.java
> +        String slugId = article.getTitle().trim().replace(" ", "-") +
slugId를 만드는 행위는 분리할 수 있지 않을까요?

2023-05-02 12:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/comment/domain/dto/AddCommentResponseDto.java
> +    private AddCommentDTO comment;
요건 왜 Dto로 안하고 DTO로 되어 있을까요? 일관성 있게 코드를 작성하면 좋을 것 같습니다.

2023-05-02 12:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/comment/domain/dto/GetCommentAuthorDto.java
> +@Getter
import문과 `@Getter`를 띄워주세요.

2023-05-02 12:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/comment/domain/dto/GetCommentAuthorDto.java
> +
불 필요한 공백은 제거해주세요.

2023-05-02 12:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/comment/domain/dto/GetCommentDto.java
> +                         ) {
생성자 파라미터 선언이 기존 형식들과 다른 것 같습니다. 일관되게 맞춰주시면 좋을 것 같아요.

2023-05-02 12:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/comment/domain/repository/CommentRepository.java
> +    GetCommentDto getCommentById(Long id);
이미 CommentRepository라고 객체가 네이밍이 되어있기 때문에, add, getById와 같이 메서드 이름을 줄여주는 것이 좋을 것 같은데 어떻게 생각하실까요?

2023-05-02 12:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/app/ArticleService.java
> +    GetUserDto getArticleAuthor(Long userId);
ArticleService라고 객체의 이름이 정해졌는데, 메서드 이름을 줄여볼 수 있지 않을까요?

2023-05-02 12:49 UTC, Rebwon commented on src/test/java/com/dss/realworld/user/domain/repository/UserRepositoryTest.java
> +    private void clearTable() {
중복적으로 clearTable을 각 테스트마다 하고 있는데, 테스트 도우미 객체를 만들어서 중복을 제거해볼 수 있지 않을까요?

2023-05-02 12:49 UTC, Rebwon commented on src/test/java/com/dss/realworld/article/api/ArticleControllerTest.java
> +        CreateArticleRequestDto.CreateArticleDto article = CreateArticleRequestDto.CreateArticleDto.builder()
Given 절에서 반복적인 객체 생성으로 인해 코드 가독성이 떨어지는데, Factory 클래스나 Fixture 클래스 모음을 만들어서 가독성 있게 테스트 코드를 작성해보면 어떨까요?

2023-05-02 13:16 UTC, sdongpil commented
넵 확인했습니다 감사합니다.

2023-05-03 03:47 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleRequestDto.java
> +        String slugId = article.getTitle().trim().replace(" ", "-") +
예 분리할 수 있습니다. 수정하겠습니다.

2023-05-03 03:53 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +        article = new CreateArticleDto(slug, title, description, body, tagList, createdAt, updatedAt, false, 0, author);
CreateArticleResponseDto 생성자 파라미터 중 GetUserDto를 ArticleAuthorDto로 변환하기 위해 넣었습니다.
지금 다시 생각해 보니 GetUserDto에서 ArticleAuthorDto로 변환하는 기능을 넣는 게 좋을 것 같습니다.
변환 작업이 자꾸 상위 계층으로 넘어가서 보기 좋지 않다고 생각합니다. 🙂

2023-05-03 04:01 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/ArticleAuthorDto.java
> +        this.following = false;
생성자를 만들 때 지역변수를 초기화하는 것처럼 습관적으로 넣은 것 같습니다. 수정하겠습니다.
그리고 DB에서 받은 GetUserDto를 ArticleAuthorDto로 변환하기 위해 생성자 파라미터로 선언했습니다.
ArticleAuthorDto는 Single Article이 API 호출을 통해 반환될 때 필요한 필드를 전달하는 역할을 합니다.

2023-05-03 04:23 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +        article = new CreateArticleDto(slug, title, description, body, tagList, createdAt, updatedAt, false, 0, author);
[Single Article API 반환 형식](https://realworld-docs.netlify.app/docs/specs/backend-specs/api-response-format#single-article)에 맞추려고 
private final CreateArticleDto article; 필드를 CreateArticleResponseDto 클래스로 감싼 형태가 되었습니다.

2023-05-03 04:31 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +        article = new CreateArticleDto(slug, title, description, body, tagList, createdAt, updatedAt, false, 0, author);
CreateArticleResponseDto 생성자에서 DB에서 불러온 getArticleDto, getUserDto 정보를 조합해 CreateArticleResponseDto의 필드인 CreateArticleDto article에 객체를 주입하려고 했습니다.

2023-05-03 04:32 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +public class ArticleServiceImpl implements ArticleService {
테스트를 하기 전에 인터페이스에 적용해도 구현 클래스에서 동작하는지 확실하지 않아 둘 다 정의한 것입니다. 정상 작동 확인 후 삭제하겠습니다.

2023-05-03 04:34 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        }
테이블이 비어 있으면 maxArticleId를 구하는 쿼리가 null을 반환하여 0L으로 처리되도록 했습니다.

2023-05-03 04:50 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        if (Optional.ofNullable(foundArticle).isEmpty()) {
예 맞습니다. 그래서 다음과 같이 수정해봤습니다.

    @Override
    public void deleteArticle(String slug, Long userId) {
        Optional<GetArticleDto> foundArticle = articleRepository.getArticleBySlug(slug);
        if (isEmpty(foundArticle)) throw new ArticleNotFoundException();

        if (isAuthorMatch(userId, foundArticle)) throw new ArticleAuthorNotMatchException();

        articleRepository.deleteArticle(foundArticle.get().getId());
    }

2023-05-03 05:03 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        if (foundArticle.getUserId().compareTo(userId) != 0) {
예 맞습니다. 반영하겠습니다.

2023-05-03 05:25 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/Article.java
> +    private LocalDateTime updatedAt = LocalDateTime.now();
예 맞습니다. MyBatis를 통해 insert문으로 전달될 마지막 파라미터 역할을 합니다.

다시 보니 DB에 기본값이 설정되어 있어서 아래와 같이 수정해도 될 것 같습니다.
private final LocalDateTime createdAt = null;
private final LocalDateTime updatedAt = LocalDateTime.now();

2023-05-03 07:28 UTC, sdongpil commented
멘토님, 도우미객체 사용해 clearTable() 처리하는 방법을 조금 더 풀어서 설명해 주실 수 있으실까요? 
그 외 나머지는 수정 완료 했습니다.

2023-05-03 11:41 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +        article = new CreateArticleDto(slug, title, description, body, tagList, createdAt, updatedAt, false, 0, author);
반환 형식을 맞추는 방법이 저거 밖에 없나요? 다른 방식은 찾아보실 생각이 없으신가요?

2023-05-03 11:42 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +public class ArticleServiceImpl implements ArticleService {
음.. `@Transactional`의 동작 원리를 아셨다면 둘 다 정의하지 않고도 사용 가능했을 것 같은데, 한번 찾아보시죠.

2023-05-03 11:44 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        }
maxArticleId라는 개념은 정확하게 어떤 개념인가요? 잘 이해가 되지 않아서요. 설명 부탁드립니다.

2023-05-03 11:45 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/domain/Article.java
> +    private LocalDateTime updatedAt = LocalDateTime.now();
domain으로 정의한 Article은 한번 생성하고 나면 바뀌지 않는다는게 좀 이상하네요. 유저가 Article 정보를 바꿀 때는 어떻게 처리하실 계획이신가요?

2023-05-03 11:49 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        return foundArticle.get().getUserId().compareTo(userId) != 0;
get().getUserId()로 Tell Don't Ask 원칙 위반인데, 이걸 어떻게 처리하면 좋을까요?

2023-05-03 11:50 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        if (isEmpty(foundArticle)) throw new ArticleNotFoundException();
isEmpty를 더 유연하게 한 줄로 처리하는 방법은 없을까요?

2023-05-03 11:50 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleRequestDto.java
> +        return title.trim().replace(" ", "-") + "-" + (maxArticleId + 1);
Slug를 생성하는 로직을 domain 객체로 옮겨볼 순 없을까요?

2023-05-03 11:52 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +public class ArticleServiceImpl implements ArticleService {
[공식 문서](https://share.glasp.co/oyjg0o35je8krcjy/?p=QqQC6XKKf9rF7Xdd8xDE)를 찾아 보니 클래스에 지정하는 걸 권장한다고 합니다. 감사합니다.

2023-05-03 11:53 UTC, Rebwon commented
clearTable() 하는 로직이 여러곳에 흩어져 있는데, 전부 다 테이블 초기화하는 로직이니까 모아서 한번에 처리하는 방법으로 만들면 되지 않을까요?

2023-05-03 12:10 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +        article = new CreateArticleDto(slug, title, description, body, tagList, createdAt, updatedAt, false, 0, author);
다음과 같은 [정적 팩토리 메서드 of() 형태](https://velog.io/@cjh8746/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9CStatic-Factory-Method#%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-%EB%AA%85%EB%AA%85%EB%B0%A9%EC%8B%9D)로 가능합니다. 수정하겠습니다. 🙂

    public static ErrorResponse of(String errorCode, String errorMessage) {
        return ErrorResponse.builder()
                .errorCode(errorCode)
                .errorMessage(errorMessage)
                .build();
    }

2023-05-03 12:13 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +        article = new CreateArticleDto(slug, title, description, body, tagList, createdAt, updatedAt, false, 0, author);
음.. 제 얘긴 그게 아니라 article 변수를 만들고 또 그안에 Nested Class로 Article에 해당하는 정보를 담는 Class를 생성하셨는데 그렇게 하신 의도가 json 응답 포맷을 맞추기 위함이 아닌가요? json 응답 포맷을 맞추는 방식을 다른 것을 찾아보시면 어떻겠냐는 얘기입니다.

2023-05-03 12:16 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        }
Article 테이블의 PK 중에서 가장 나중에 부여된 번호이고 Article 테이블의 slug 속성값의 접미사로 사용됩니다.
Article API spec을 보면 URI에 :slug가 사용되는데요, Article 1개를 특정하는 역할을 합니다.

2023-05-03 12:32 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/Article.java
> +    private LocalDateTime updatedAt = LocalDateTime.now();
지금은 사용자가 Article 등록 요청 시 @builder를 통해 Article 객체가 새로 생성되어 DB에 추가됩니다.
수정 요청 시에도 update문에 들어갈 정보를 @builder를 통해 만들어진 Article 객체에 담아 DB에 전달할 예정이었습니다.

수정 시에도 Article이 DB에 똑같이 전달이 된다면 의미상 final이 없는 게 자연스럽다고 생각합니다.
final 없이 구현해보겠습니다.

2023-05-03 13:01 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleRequestDto.java
> +        return title.trim().replace(" ", "-") + "-" + (maxArticleId + 1);
slug를 domain 객체로 만들고 그 안에서 정적 팩토리 메서드로 slug를 생성하도록 바꿔보겠습니다.

2023-05-03 13:58 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +        article = new CreateArticleDto(slug, title, description, body, tagList, createdAt, updatedAt, false, 0, author);
예 알겠습니다. @JsonRootName 사용해서 맞춰보겠습니다.

2023-05-03 18:25 UTC, sdongpil commented
> clearTable() 하는 로직이 여러곳에 흩어져 있는데, 전부 다 테이블 초기화하는 로직이니까 모아서 한번에 처리하는 방법으로 만들면 되지 않을까요?

넵 변경 해보겠습니다

2023-05-04 03:30 UTC, a11chan commented on src/test/java/com/dss/realworld/user/domain/repository/UserRepositoryTest.java
> +    private void clearTable() {
AOP 적용해서 @Around로 처리하는 방법은 어떨까요? 
의도하신 것과 다른 방향이라면 검색 키워드 힌트 좀 부탁드립니다. 🙂

2023-05-04 04:03 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/domain/Article.java
> +    private LocalDateTime updatedAt = LocalDateTime.now();
Article 객체의 데이터가 애플리케이션 생명 주기에서 변해야 하면 final을 붙이지 않고, 만약 변하지 않아도 된다면 final을 붙여서 구현해주시면 됩니다.

2023-05-04 04:03 UTC, Rebwon commented on src/test/java/com/dss/realworld/user/domain/repository/UserRepositoryTest.java
> +    private void clearTable() {
AOP 방식을 제안해주셨으니, AOP로 구현해보시죠.

2023-05-04 04:11 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        }
Article이 생성될 때 slug도 만들어지는데 Article Id를 이용해 slug가 중복되지 않게 하려고 구했습니다.

2023-05-04 04:12 UTC, a11chan commented on src/test/java/com/dss/realworld/user/domain/repository/UserRepositoryTest.java
> +    private void clearTable() {
예 알겠습니다.

2023-05-04 04:13 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/Article.java
> +    private LocalDateTime updatedAt = LocalDateTime.now();
예 알려주신 부분 고려해서 구현하겠습니다.

2023-05-05 07:38 UTC, sdongpil commented
clearTable() 로직 분리 외 수정 완료했습니다. 확인 부탁드립니다!

2023-05-05 13:00 UTC, Rebwon commented on src/main/java/com/dss/realworld/comment/domain/repository/CommentRepository.java
> +    GetCommentDto getById(Long id);
CommentRepository면 Comment를 반환해야 할텐데, 왜 Dto를 반환할까요?

2023-05-05 13:00 UTC, Rebwon commented on src/main/java/com/dss/realworld/article/domain/repository/ArticleRepository.java
> +    GetArticleDto getById(Long id);
ArticleRepository면 Article을 반환하는게 일반적인데, 왜 Dto를 반환해야 할까요?

2023-05-05 13:01 UTC, Rebwon commented on src/main/java/com/dss/realworld/user/api/AddUserResponseDto.java
> +        this.email = getUserDto.getEmail();
여기도 생성자 파라미터에 필요한 정보만 받고, 응답으로 넘겨주는 객체니까 final로 필드를 처리해도 무방해보입니다.

2023-05-05 13:02 UTC, Rebwon commented on src/main/java/com/dss/realworld/user/app/UserServiceImpl.java
> +        return userRepository.getByEmail(user.getEmail());
UserRepository도 Article,CommentRepository와 마찬가지로 User를 넘겨야 하는게 아닌가 싶네요. Service 객체의 메서드 설계가 입력과 반환을 Dto로 하더라도 내부적인 구현에서는 도메인 객체로 로직을 표현해야 맞지 않나 싶네요.

인터페이스를 쓴다는 건 내부 구현을 숨긴다는 의미인데, 내부 구현을 숨기는 이점을 얻고 있지 못한 것 같습니다.

2023-05-05 13:03 UTC, Rebwon commented on src/main/java/com/dss/realworld/user/domain/repository/UserRepository.java
> +    GetUserDto getById(Long id);
이 부분도 User 객체를 반환 타입으로 선언하는게 맞을 거 같네요.

2023-05-05 15:46 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/Slug.java
> +        return title.trim().toLowerCase().replace(" ", "-") + "-" + (maxArticleId + 1);
다음과 같이 구현해봤습니다.
"SlugVO"처럼 접미사로 "VO"를 붙여야 할까요?
틀린 점 알려주시면 감사하겠습니다. 🙂

```java
package com.dss.realworld.article.domain;

import java.util.Objects;

public final class Slug {

    private final String title;
    private final Long maxArticleId;

    private Slug(final String title, final Long maxArticleId) {
        this.title = title;
        this.maxArticleId = maxArticleId;
    }

    public static Slug of(final String title, final Long maxArticleId) {
        return new Slug(title, maxArticleId);
    }

    public String toString() {
        return this.title.trim().toLowerCase().replace(" ", "-") + '-' + (this.maxArticleId + 1);
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if ((o == null) || (getClass() != o.getClass())) return false;
        final Slug slug = (Slug) o;
        return title.equals(slug.title) && maxArticleId.equals(slug.maxArticleId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(title, maxArticleId);
    }
}
```

2023-05-07 03:05 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/Slug.java
> +        return title.trim().toLowerCase().replace(" ", "-") + "-" + (maxArticleId + 1);
알려주셔서 감사합니다. 🙂 toString()이란 이름은 바람직하지 않아서 getString()으로 수정했습니다.

2023-05-07 03:19 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleRequestDto.java
> +    public Article convertToArticle(Long logonUserId, Long maxArticleId) {
convert로 수정하였습니다.

2023-05-07 03:23 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        articleRepository.create(article);
JPA에서의 save(), persist()와 비슷한 기능을 하네요. 
반환 값이 없는 메서드이므로 persist로 수정했습니다. 🙂

2023-05-07 03:29 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/dto/GetArticleDto.java
> +    }
삭제하려고 하는 User와 Article의 작성자가 일치하는지 검증하는 문제이므로
작성자의 정보를 가지고 있는 Article의 책임일 때가 더 어울립니다.

2023-05-07 03:32 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/dto/GetArticleDto.java
> +    }
이 부분은 repository에서 사용하는 DTO들을 도메인 클래스(Article, Comment, User, ...)로 수정할 때 반영하겠습니다.

2023-05-07 03:34 UTC, a11chan commented on src/main/java/com/dss/realworld/comment/api/dto/AddCommentResponseDto.java
> +    public AddCommentResponseDto(GetCommentDto foundComment, GetUserDto foundUser){
Java Object를 JSON으로 직렬화할 때 기본 생성자가 있어야 하는 줄로 잘못 알고 있어서 그랬습니다.
final로 수정하겠습니다.

2023-05-07 03:35 UTC, a11chan commented on src/main/java/com/dss/realworld/comment/api/dto/CommentAuthorDto.java
> +    CommentAuthorDto(GetUserDto getUserDto) {
예 반영하겠습니다.

2023-05-07 03:58 UTC, a11chan commented on src/main/java/com/dss/realworld/comment/app/CommentServiceImpl.java
> +        foundArticle.orElseThrow(ArticleNotFoundException::new);
이렇게 했는데 의도하신 바가 맞나요?
```java
GetArticleDto foundArticle = articleRepository.getBySlug(slug).orElseThrow(ArticleNotFoundException::new);
```

2023-05-07 04:00 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        if (foundArticle.get().isAuthorMatch(userId)) throw new ArticleAuthorNotMatchException();
if문 쪽은 잘 떠오르지 않아서 일단 이렇게 했습니다.
IntelliJ는 `assert !foundArticle.isAuthorMatch(userId);` 이렇게 추천하는데, 던지는 예외가 달라서 보류했습니다.
```java
GetArticleDto foundArticle = articleRepository.getBySlug(slug).orElseThrow(ArticleNotFoundException::new);

if (foundArticle.isAuthorMatch(userId)) throw new ArticleAuthorNotMatchException();
```

2023-05-07 04:07 UTC, a11chan commented on src/main/java/com/dss/realworld/article/app/ArticleServiceImpl.java
> +        if (foundArticle.get().isAuthorMatch(userId)) throw new ArticleAuthorNotMatchException();
이렇게 수정했는데 맞는지 알려주시면 감사하겠습니다.
```java
GetArticleDto foundArticle = articleRepository.getBySlug(slug).orElseThrow(ArticleNotFoundException::new);

assert !foundArticle.isAuthorMatch(userId) : new ArticleAuthorNotMatchException();
```

2023-05-07 04:44 UTC, a11chan commented on src/main/java/com/dss/realworld/comment/domain/repository/CommentRepository.java
> +    GetCommentDto getById(Long id);
MyBatis가 쿼리 결과를 Java로 매핑할 때 기본 생성자가 없어서 오류가 난 적이 있는데
그때 기본 생성자를 추가하면서 final을 다 제외한 Dto를 따로 만들었습니다.
다음 글을 참고하여 도메인 객체를 반환하도록 수정하겠습니다.
https://zzang9ha.tistory.com/420

2023-05-07 04:45 UTC, a11chan commented on src/main/java/com/dss/realworld/article/domain/repository/ArticleRepository.java
> +    GetArticleDto getById(Long id);
[전 글](https://github.com/DSS-1st/realworld/pull/11#discussion_r1186781600)에서 알려드린 이유과 같습니다. Article로 수정하겠습니다.

2023-05-07 04:46 UTC, a11chan commented on src/main/java/com/dss/realworld/user/api/AddUserResponseDto.java
> +        this.email = getUserDto.getEmail();
예 반영하겠습니다.

2023-05-07 04:47 UTC, a11chan commented on src/main/java/com/dss/realworld/user/app/UserServiceImpl.java
> +        return userRepository.getByEmail(user.getEmail());
예 반영하겠습니다.

2023-05-07 04:48 UTC, a11chan commented on src/main/java/com/dss/realworld/user/domain/repository/UserRepository.java
> +    GetUserDto getById(Long id);
전체적으로 MyBatis 매핑 원리 이해가 부족한 결과로 생긴 문제들이네요. 수정하겠습니다. 🙂

2023-05-07 04:48 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/CreateArticleResponseDto.java
> +    public CreateArticleResponseDto(GetArticleDto getArticleDto, GetUserDto getUserDto) {
예 수정하겠습니다.

2023-05-07 04:49 UTC, a11chan commented on src/main/java/com/dss/realworld/article/api/dto/ArticleAuthorDto.java
> +    ArticleAuthorDto(GetUserDto getUserDto) {
예 수정하겠습니다.

2023-05-07 06:26 UTC, a11chan commented
안녕하십니까 멘토님, 현재까지 완료된 작업입니다.
나머지 작업은 최대한 해보고 오늘 20시에 뵙겠습니다.

객체에서 필요한 파라미터만 넘기기
[x] ArticleAuthorDto - 16
[x] CommentAuthorDto.java - 19
[x] CreateArticleResponseDto - 29
[ ] AddCommentResponseDto.java - 19

GetArticleDto -> Article
[ ] isAuthorMatch() -> 도메인 클래스로 이관

Dto -> 도메인 클래스 반환
[ ] CommentRepository.java - 22
[ ] ArticleRepository.java - 22
[ ] UserServiceImpl.java - 28
[ ] UserRepository.java - 17, 19

-----
[ ] clearTable() AOP로 추출

2023-05-07 10:38 UTC, a11chan commented
객체에서 필요한 파라미터만 넘기기
v ArticleAuthorDto - 16
v CommentAuthorDto.java - 19
v CreateArticleResponseDto - 29
[ ] AddCommentResponseDto.java - 19

Dto -> 도메인 클래스 반환
[ ] CommentRepository.java - 22
v ArticleRepository.java - 22
v UserServiceImpl.java - 28
v UserRepository.java - 17, 19

GetArticleDto -> Article
v isAuthorMatch() -> 도메인 클래스로 이관

-----
clearTable() AOP로 추출

2023-05-07 11:37 UTC, Rebwon commented
GitHub main 
- 3번 브랜치까지 머지된 상황.

GitHub feature-4_add_comments
- main 브랜치와 코드 충돌이 나서 conflict이 발생한 상황. 따라서 머지가 안됨. -> 해결해야 함.

Local Git
- Local main 브랜치를 최신화
   - git pull
- git checkout feature-4_add_comments
- git merge main -> 충돌 발생
- 충돌 해결
- git add .
- git commit
   - :wq
- git push origin feature-4_add_comments

feature-3_add_comments -> feature-4_add_comments

2023-05-12 12:09 UTC, merged