feat : User 생성/업데이트 시각 추가
DSS-1st/realworld pull request #2
Opened 2023-04-17 05:33 UTC by a11chan

안녕하십니까, 현재까지 작업한 내용 최초 커밋입니다.
회원가입 요청/완료 시 반환되는 JSON 객체 처리 로직 개발 중입니다.

일단 인증이 필요하지 않은 기능부터 개발 진행 예정입니다.
이에 대한 내용은 다음 링크를 참고 부탁드립니다.
https://allchan.notion.site/RealWorld-384b3d9131c64a28a43619ff02de17e3

2023-04-17 05:49 UTC, woogiekim reviewed
아주 작게 작업을 나누신것 좋은거같습니다.
몇가지 아쉬운점 적어봅니다.

1. 객체 생성시 유효성 검사가 없습니다.
2. 테스트 코드가 없습니다.
3. Users 라고 클래스명을 짓는것은 어색하다는 생각이 들긴합니다.

위에 언급한 내용들이 없다면 안전하게 User 객체를 만들기 어렵다고 봅니다.

2023-04-17 05:49 UTC, woogiekim commented on src/main/java/com/dss/realworld/user/Users.java
> +        this.updatedAt = updatedAt;
생성되고 업데이트 되는 시간을 매개변수로 받을 필요가 있을까 싶습니다.

2023-04-17 06:00 UTC, a11chan commented on src/main/java/com/dss/realworld/user/Users.java
> +        this.updatedAt = updatedAt;
감사합니다. 보완해서 다시 PR 드리겠습니다.

2023-04-17 15:17 UTC, sdongpil commented
태욱님 언급하신 내용들 수정해봤습니다. 테스트코드도 금방 작성해보겠습니다..!

2023-04-19 03:53 UTC, woogiekim requested changes
어제 리뷰 내용 정리입니다.

1. User 생성 성공 및 실패에 대한 테스트 코드 작성
2. createdAt, updatedAt 원복 및 생성자의 매개변수를 통한 매개변수 제거
3. image 는 어떤 형태로 저장할것인가에 대한 고민 예) s3를 이용한다면 풀경로를 넣을것인가 이미지키만 넣을것인가 등

위 내용 반영해주시면 좋겠습니다.

2023-04-19 21:52 UTC, woogiekim approved these changes
리뷰반영 확인했습니다.
머지하시기전에 아래 내용 확인 하시고
다음 기능 진행하시면 되겠습니다.

1. 유효성검사하는 부분과 필드값 세팅 하는 부분이 교차되어 있는데 유효성 검사와 필드세팅 부분을 분리해서 코드작성 하는게 더 가독성에 좋아보입니다.

현재 코드
```
this.id = id;
Asserts.isTrue(...);
this.username = username;
Asserts.isTrue(...);
```

제안코드
```
Asserts.isTrue(...);
Asserts.isTrue(...);

this.id = id;
this.username = username;
```
2. api 리턴타입이 도메인객체 인데, DTO로 변경 하는것 다음 작업에 진행하는 편이 좋겠습니다.
3. PR 이름과 무관한 코드를 더 넣으셨는데 의식하시면서 자제하는 편이 더 좋겠습니다.
(Get 하는 부분에 대한 코드들)
4. 유저테스코드 이름 중에 생성 실패케이스가  fail... 로 시작하는데 생성 테스트만 할것은 아니기에 보다 명확한 이름으로 변경하는 편이 좋겠습니다.

2023-04-19 22:27 UTC, a11chan commented
안녕하십니까 멘토님, 최신 피드백 감사합니다. :slightly_smiling_face:
바로 반영하고 다음 작업 이어가겠습니다.

피드백 중에 3번을 보니 궁금한 점이 생겨 질문 드립니다.
PR 이름과 관련된 코드만 커밋해야 한다는 뜻으로 이해하면 될까요?
첨부한 스크린샷 보시면 선택된 커밋 외엔 PR과 무관한데요,
다음 커밋시에는 PR과 커밋 내용을 일치시키면 될까요?

예를 들자면 다음 작업은 "User 도메인 유효성 검사 위치, 테스트 코드명 수정" 이면
커밋 내용과 PR 이름을 "fix : User 도메인 유효성 검사 위치, 테스트 코드명 수정"
([realworld 공식 깃헙 PR Tab](https://github.com/gothinkster/realworld/pulls)에 가보니 이런 식으로 되어 있었습니다).
이렇게 해도 되는지 궁금합니다.

![image](https://user-images.githubusercontent.com/85478918/233213011-2731a534-7091-4c35-b481-710d2676e6d9.png)

2023-04-20 01:15 UTC, woogiekim commented
PR명과 무관하다는것은 이부분과 관련이있습니다
생성일 수정일 추가인데
조회관련된부분까지 추가되어있습니다.

아무래도 음성으로 리뷰할때 이런거 저런거 이야기한것이 혼선이 있었나보긴합니다.

![image](https://user-images.githubusercontent.com/58969072/233231474-c5e6b17d-627c-40cd-911f-8dc5ffe2e124.jpeg)

---
- PR과 벗어나는 작업을 하면 범위가 계속 늘어나서 호흡이 길어지고 컨텍스트가 흐려집니다.

- 깃컨벤션은 정해서 하기 나름이라고 저는 생각합니다. 보통 PR명이 아니라 피쳐명이나 이슈아이디 같은것을 프리픽스로 쓰거나 하는거같습니다.

2023-04-20 01:34 UTC, merged

2023-04-20 01:40 UTC, a11chan commented
감사합니다. 알려주신 내용 협의하여 진행하겠습니다.