1. 회원가입 API 개발_addUser 메소드 리턴타입 변경(Entity => DTO)
DSS-1st/realworld pull request #4
Opened 2023-04-20 13:57 UTC by sdongpil

오늘 아침에 리뷰해주신 내용중 2번 반환타입변경에 대한 반영 내용입니다.

검토 부탁드립니다.

2023-04-21 06:43 UTC, woogiekim requested changes
두분 작업하시는것이 뭔가 싱크가 오묘하게 맞물려있네요

없어도될 User 유효성검사코드와 UserTest 관련 코드가 함께 있는것이 의아합니다.

리뷰남겼습니다. 확인부탁드립니다.

2023-04-21 06:43 UTC, woogiekim commented on src/main/java/com/dss/realworld/user/api/AddUserResponseDto.java
> +    }
이 코드가 무슨 의미인지  잘 모르겠습니다.
빌더가 필요하다는 생각이 안드네요.

GetUserDto -> AddUserDto

이런식으로 변환해주는 작업을 AddUserResponseDto에서 진행하는것이 어떤가 싶긴하네요.

2023-04-21 07:46 UTC, a11chan commented
싱크가 맞물려 있는 이유는 제 실수로
이 PR에 해당하는 branch를 만들 때 main branch에서 만들지 않고
이전 PR에 해당하는 branch에서 생성하자고 해서 그런 것 같습니다.

2023-04-21 08:41 UTC, woogiekim commented
넵 다른 작업에서는
서로 연관있는 로직이 아니라면 맞물려서 작업은 지양하는 것이 좋겠습니다.

2023-04-21 10:35 UTC, a11chan commented on src/main/java/com/dss/realworld/user/api/AddUserResponseDto.java
> +    }
그 방법이 더 이해하기 좋을 것 같습니다. 수정하겠습니다.

2023-04-24 01:41 UTC, woogiekim approved these changes
get... 이름으로
변환하는것보다 생성자가 더 좋겠다는 생각이 들긴합니다.

한 주간 고생하셨습니다!

2023-04-24 05:17 UTC, a11chan commented
반영하여 Merge 하겠습니다. 😊 감사합니다.

2023-04-24 13:37 UTC, merged